import type { ParsedTask, RequiredPermission } from "../types.js";
import type { AgentTool, CommandLine } from "./agent.js";
import { getAgentInstructions } from "./shared-prompt.js";

export function renderPolicyToml(allowedTools: string[]): string {
  const list = allowedTools.map((t) => JSON.stringify(t)).join(", ");
  return [
    "# Generated by Palmier — do not edit.",
    "[[rule]]",
    `toolName = [${list}]`,
    `decision = "allow"`,
    "priority = 100",
    "",
    "[[rule]]",
    `toolName = "*"`,
    `decision = "deny"`,
    "priority = 1",
    "",
  ].join("\n");
}

export const geminiAgent: AgentTool = {
  command: "gemini",
  promptCommandLineArgs: ["--prompt"],
  versionCommandLineArg: "--version",
  supportsPermissions: true,
  supportsYolo: true,
  suppressStdErr: false,
  npmPackage: "@google/gemini-cli",

  getTaskRunCommandLine(task: ParsedTask, followupPrompt?: string, extraPermissions?: RequiredPermission[] | "yolo"): CommandLine {
    const yolo = extraPermissions === "yolo";
    const prompt = followupPrompt ?? getAgentInstructions(task);
    const args = ["--approval-mode", yolo ? "yolo" : "auto_edit"];
    const files: CommandLine["files"] = [];

    if (!yolo) {
      const tools = ["run_shell_command(curl)", "web_fetch"];
      const allPerms = [...(task.frontmatter.permissions ?? []), ...(extraPermissions ?? [])];
      for (const p of allPerms) {
        tools.push(p.name);
      }
      const policyPath = "gemini-policy.toml";
      files.push({ path: policyPath, content: renderPolicyToml(tools) });
      args.push("--admin-policy", policyPath);
    }

    if (followupPrompt) {args.push("--resume");}
    // Read prompt from stdin to avoid command-line length limits.
    args.push("--prompt", "-");

    return { args, stdin: prompt, ...(files.length > 0 ? { files } : {}) };
  },
};
